name: Go Vulnerability Check Analysis

on:
  workflow_call:

jobs:
  govulncheck:
    name: Run GoVulncheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        working-directory: ./backend
        run: govulncheck ./...
