name: Security Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    uses: ./.github/workflows/sonarcloud.yml
    secrets: inherit

  trivy:
    uses: ./.github/workflows/trivy.yml
    secrets: inherit

  gosec:
    uses: ./.github/workflows/gosec.yml
    secrets: inherit

  govulncheck:
    uses: ./.github/workflows/govulncheck.yml
    secrets: inherit