name: Security Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  security-events: write
  pull_requests: write

jobs:
  sonar:
    uses: ./.github/workflows/sonarcloud.yml
    secrets: inherit

  trivy:
    uses: ./.github/workflows/trivy.yml
    secrets: inherit
    
  gosec:
    uses: ./.github/workflows/gosec.yml

  govulncheck:
    uses: ./.github/workflows/govulncheck.yml
